### ISSUE TITLE
Feature: pip-sync --dry-run should return a non-zero exit code if changes were to occur

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#1166]
#### What's the problem this feature will solve?
I'm looking to add a pre-commit hook to check the environment is up to date

```
-   repo: local
    hooks:
    -   id: pip-sync
        name: pip-sync check
        entry: pip-sync --dry-run
        language: system
        always_run: true
        pass_filenames: false
```

#### Describe the solution you'd like
```
$ pip-sync --dry-run
Would install:
  numpy==1.18.5
$ $?
2
```

#### Alternative Solutions
various | awk stuff

#### Additional context
NA
