### ISSUE TITLE
pre-commit is in another folder than the project

### ISSUE THREAD

**Issue by MartinThoma** [jazzband/pip-tools#1207]
I receive a `FileNotFoundError: [Errno 2] No such file or directory: 'myproject/_version.py'`, because I have this structure:

```
git root
├── .pre-commit-config.yaml
├── README.md
└── web
    ├── myproject
    │   ├── app.py
    │   ├── __init__.py
    │   ├── _version.py
    │   └── wsgi.py
    ├── setup.py
    ├── tests
    └── tox.ini
```

#### Environment Versions

1. OS Type: Ubuntu 20.04
1. Python version: Python 3.8.3
1. pip version:  pip 20.2.2 from /home/moose/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip (python 3.8)
1. pip-tools version: pip-compile, version 5.2.1

#### Steps to replicate

Having the above folder structure and this .pre-commit-config.yaml:

```yaml
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.0.0
    hooks:
      - id: pip-compile
        files: ^web/setup\.py$
```

#### Expected result

A `requirements.txt` within the `web` directory

#### Actual result

Weird ... now I get:

```
pip-compile..............................................................Failed
- hook id: pip-compile
- exit code: 2

Usage: pip-compile [OPTIONS] [SRC_FILES]...

Error: Invalid value: If you do not specify an input file, the default is requirements.in or setup.py
```

I'm not sure what changed. Anyway, it is not working :-/

**Comment by atugushev** [comment]
Hello @MartinThoma,

This should work:

```yaml
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.0.0
    hooks:
      - id: pip-compile
        files: ^web/setup\.py$
        args: [web/setup.py]
```
