### ISSUE TITLE
pre-commit does not detect changes in .in files

### ISSUE THREAD

**Issue by MartinThoma** [jazzband/pip-tools#1208]
I've added the pre-commit hook so that I cannot forget to compile the .in files to .txt files. It passes, but does not act when it should.

#### Environment Versions

1. OS Type: Ubuntu 20.04
1. Python version: Python 3.8.3
1. pip version:  pip 20.2.2 from /home/moose/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip (python 3.8)
1. pip-tools version: pip-compile, version 5.3.1

#### Steps to replicate

The pre-commit-config.yaml is:

```
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      - id: pip-compile
        files: ^setup\.py|requirements-dev\.in|requirements-lint\.in$
```

If you want a full example:

```
git clone https://github.com/MartinThoma/HASY.git
cd HASY
sed -i '/flake8-comprehensions/d' requirements-lint.in
pre-commit run --all-files
```

#### Expected result

Updated `requirements-lint.txt`

#### Actual result

No change in `requirements-lint.txt`, but pre-commit passes

**Comment by MartinThoma** [comment]
I solved my problem. You might be interested in [check-pip-compile](https://github.com/MartinThoma/check-pip-compile):

```
-   repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.0
    hooks:
    -   id: check-pip-compile
        args: ['.']  # it's recommended to specify the files you want
```

**Comment by atugushev** [comment]
Hello @MartinThoma,

Thanks for the issue! You should use a separate hook for each input requirement file, for example:


```yaml
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        files: ^setup\.py$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-lint.in
        args: [requirements-lint.in]
        files: ^requirements-lint\.(in|txt)$
```
