### ISSUE TITLE
Add possibility to store pip-tools configuration in configuration files

### ISSUE THREAD

**Issue by Mogost** [jazzband/pip-tools#1435]
The [README](https://github.com/jazzband/pip-tools#configuration) says that I can specify a custom command to compile.
This generally forces you to read the `requirements.txt` instead of just running pip-compile
My suggestion is to use a configuration file such as `pyproject.toml` (other formats are fine too) to save such settings for the project.

The `pyproject.toml` file could look like this:
```
[tool.pip-tools]
allow-unsafe = true
output-file = requirements-custom.txt
generate-hashes = true
...
```

Then, when you run `pip-compile` without parameters, `pip-tools` will automatically apply the configuration set for the project and will not require passing the necessary arguments.

Partly because `pip-tools` has no configuration file, tools like dependabot (which use pip-tools internally to compile deps) have to look at the project first and parse the existing requirements.txt. And then run pip-compile with the right parameters.
And instead of just looking in the configuration file and seeing that the output file should be hashed, dependabot check output file for the `--hash=sha256` substring. Here is dependabot example https://github.com/dependabot/dependabot-core/blob/e2ad9b9a7014dac6d8d06db3fc9df78efc24a2c4/python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb#L415

**Comment by craigds** [comment]
I found this issue while looking into options for renovatebot/renovate#2334 to support pip-compile workflows. It's quite complex to do so at present; having a config file specify the pip-compile args would make it much simpler.

Multiple in/txt files can exist and have layered dependencies between them, so a single `output-file` isn't likely to suffice.

I'd suggest maybe the `pyproject.toml` might look more like this:

```toml
[tool.pip-tools]
allow-unsafe = true
generate-hashes = true

[tool.pip-tools.file-mappings]
# maps output files back to the input files used to generate them.
"requirements/production.txt" = [ "requirements/production.in" ]
"requirements/test.txt" = [ "requirements/test.in" ]
"requirements/local.txt" =[ "requirements/production.in", "requirements/test.in" ]
```

You'd still have to run pip-compile once for each output file, but it would be able to figure out what input files to use.

**Comment by Mogost** [comment]
@atugushev Could you please review this issue?
I'm not sure if I can suggest a pull request, but I think it would be nice to get some comments from the maintainers before writing even a line of code.

Accordingly, it is worth classifying this issue with labels.

**Comment by atugushev** [comment]
This might be useful. As an idea: this could probably be implemented as a `click` plugin which would parse options from `pyproject.toml`. What do you think?

**Comment by Mogost** [comment]
> This might be useful. As an idea: this could probably be implemented as a `click` plugin which would parse options from `pyproject.toml`. What do you think?

Yes, I was thinking about this approach. In this case, it will cost one not very complicated additional decorator.

**Comment by AndydeCleyre** [comment]
I think it's a great idea to support `pyproject.toml` configs.

In addition to different output files created with different arguments, it's reasonable to have sequential workflows, where output from one pip-compile command is an input for the next.

And then there'll be more such sequences, so we'd want to label them, at least with a name (at the extreme end with an arbitrary number of 'tags', which I think too far into general task runner territory).

So if it were `yaml`, it could be like:

```yaml
tool.pip-tools:
  default:
    - args: ""
  update-stingy:
    - args: ""
  update-dev:
    - args: ""
    - args: ""
  update-security:
    - args: ""
    - args: ""

```
