### ISSUE TITLE
pre-commit running pip-compile across multiple operating systems

### ISSUE THREAD

**Issue by BTOdell** [jazzband/pip-tools#1534]
I have `pre-commit` set up using GitHub Actions to run on Linux and Windows. `pre-commit` is configured to run `pip-compile`:
```
- repo: https://github.com/jazzband/pip-tools
  rev: 6.4.0
  hooks:
    - id: pip-compile
```

The pip-compile documentation suggests running `pip-compile` for each environment combination (OS+Python):
https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile
*"As the resulting `requirements.txt` can differ for each environment, users must execute `pip-compile` on each Python environment separately to generate a `requirements.txt` valid for each said environment."*

On Linux, I currently manually run `pip-compile` and output to `requirements.txt` and on Windows I have `pip-compile` output to `requirements.win.txt`.

How do I get `pip-compile` to output to the correct requirements file depending on the operating system that pre-commit runs on?

**Comment by atugushev** [comment]
See https://github.com/pre-commit/pre-commit/issues/1455#issuecomment-628019565 for workarounds.

**Comment by BTOdell** [comment]
I was able to get it to work like this:
```yaml
- repo: https://github.com/jazzband/pip-tools
  rev: 6.4.0
  hooks:
    - id: pip-compile
      entry: ./.pre-commit-scripts/pip-compile.py
```
and then in the custom `pip-compile.py`:
```python
#!/usr/bin/env python

from subprocess import call  # nosec
from sys import platform


def main():
    if platform == "win32":
        cmd = (r"pip-compile.exe", "--output-file", "requirements.win.txt")
    else:
        cmd = ("pip-compile",)
    return call(cmd)  # nosec


if __name__ == "__main__":
    exit(main())
```

Thanks for the link!
