### ISSUE TITLE
Doc suggests `pre-commit` hook should run with `requirements.txt`

### ISSUE THREAD

**Issue by dycw** [jazzband/pip-tools#1615]
The documentation suggests the `pre-commit` hook:

```yaml
         - id: pip-compile
            name: pip-compile requirements.txt
            args: [requirements.txt]
            files: ^requirements\.(in|txt)$
```

however this is incorrect — it should be `requirements.in` which is passed in.
