### ISSUE TITLE
Support dependency groups from poetry

### ISSUE THREAD

**Issue by joshbrooks** [jazzband/pip-tools#1706]
#### What's the problem this feature will solve?

Is it possible to support Poetry groups via `--extra`? It seems that they are not (yet) supported

Poetry supports both ["extras"](https://python-poetry.org/docs/pyproject#extras) and ["dependency groups"](https://python-poetry.org/docs/managing-dependencies/#dependency-groups). pip-compile supports "extras" but (afaik) does not support "dependency groups".

Poetry encourages the use of "dependency groups" for e.g. dev requirements.

#### Describe the solution you'd like

Poetry encourages the use of a "dev" group for dependencies. From [ the Poetry docs](https://python-poetry.org/docs/managing-dependencies/#dependency-groups)
```
you might have dependencies that are only needed to test your project or to build the documentation.
```

Further, poetry encourages dev dependencies to be put into a group:
```sh
$ poetry add --dev black
The --dev option is deprecated, use the `--group dev` notation instead.
```

An an example, if I include isort in "extras" via `pip-compile -v --extra dev -o dev-requirements.txt pyproject.toml` isort will be included in requirements

```toml
[tool.poetry.dependencies]
python = "^3.7"
isort = "^5.9.3"

[tool.poetry.extras]
dev = [
  "isort",
]
```

However when I use the `dev` group it will not be inlcuded

```toml

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
```

#### Alternative Solutions

As a workaround, I can use `extra` with a list of dev dependencies.
