### ISSUE TITLE
Extras not installed by `pip-sync`

### ISSUE THREAD

**Issue by deffertern** [jazzband/pip-tools#1769]
Extras are not installed by `pip-sync` when specified in a `requirements.txt` file. For example, adding the line `example-package[extra]` to the file, and running `pip-sync`, installs `example-package` but not the dependencies specified by the `[extra]` option.

I have noticed this when installing local editable packages. But it also happens when installing packages from PyPI, for example `requests[security]`.

#### Environment Versions

1. OS Type: macOS
2. Python version: 3.9.15
3. pip version: 22.3.1
4. pip-tools version: 6.11.0

#### Steps to replicate

1. Create and activate a Python environment
2. Install requirements: `python -m pip install pip-tools setuptools`
3. Create a minimal package by creating a directory with a `pyproject.toml`:
```toml
[project]
name = "example"
version = "0.0.0"
dependencies = ["toml"]

[project.optional-dependencies]
extra = ["exceptiongroup"]
```
4. Create a `requirements.txt` with a single line:
```
-e ".[extra]"
```
5. Run pip-sync: `pip-sync requirements.txt`
6. Run `pip list`

#### Expected result

All dependencies specified by the `[extra]` option are installed (`exceptiongroup` in this case).

#### Actual result

Dependencies specified by the `[extra]` option are not installed (`exceptiongroup` in this case).
