### ISSUE TITLE
Layered requirements and pyproject.toml

### ISSUE THREAD

**Issue by gchaperon** [jazzband/pip-tools#1820]
When trying to use layered requirements in pyproject.toml, `pip-compile` fails.

Using the following `pyproject.toml` file
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "not-in-pypi"
version = "0.1.0"
dependencies = [
    "click",
    "numpy",
    "scikit-learn",
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["not-in-pypi[test]", "ipython"]
```

and running `pip-compile -o dev-requirements.txt --extra dev pyproject.toml` (same command as in the docs), `pip-compile` fails with
```console
Could not find a version that matches not-in-pypi[test] (from not-in-pypi (pyproject.toml))
No versions found
Was https://pypi.org/simple reachable?
```

However trying to install the package with `pip install .[dev]` works perfectly fine.

I _think_ this usage of optional dependencies is supported by pip, given [this](https://discuss.python.org/t/pyproject-toml-optional-dependencies-redundancy-aka-dry-extras/8428/6) and [this](https://github.com/pypa/pip/issues/10393#issuecomment-928042575) comments.

#### Environment Versions

1. OS Type : `linux`
2. Python version: `Python 3.10.9`
3. pip version: `pip 22.3.1 from /home/gchapero/projects/pip-tools-bug/env/lib/python3.10/site-packages/pip (python 3.10)`
4. pip-tools version: `pip-compile, version 6.12.3`

#### Steps to replicate

1. Using the `pyproject.toml` file described above, run `pip-compile --extra dev -o dev-requirements.txt pyproject.toml`

#### Expected result
A `dev-requirements.txt` file.

#### Actual result
An error.
