### ISSUE TITLE
Allow git dependencies in pyproject.toml format

### ISSUE THREAD

**Issue by crclark** [jazzband/pip-tools#1849]
#### What's the problem this feature will solve?

While adding a git dependency is undocumented, it seems to supported according to [this issue](https://github.com/jazzband/pip-tools/issues/1314).

However, when I try to use that format in `pyproject.toml`, I get an uninformative error message:

```
$ pip-compile --no-emit-index-url --output-file=requirements.txt --resolver=backtracking pyproject.toml                                            
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse pyproject.toml
```

#### Describe the solution you'd like

- Allow git dependencies in the above format.
- Document that this is allowed.

#### Alternative Solutions

I have not been able to find a workaround.

#### Additional context

Minimal repro `pyproject.toml`

```toml
[project]
name = "foo"
description = ""
authors = [
    { name = "foo", email = "foo@example.com"}
]
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    # uncomment the following to see the failure
    # "git+https://github.com/jazzband/django-axes@0eecff2e57dd1748ce561b9d1340f079feb278f9",
]
```
