### ISSUE TITLE
Show which extra a dependency came from

### ISSUE THREAD

**Issue by benlindsay** [jazzband/pip-tools#1850]
Currently, if you compile from pyproject.toml and specify extra requirements, you don't get to see which dependencies came from the extras. For example, with this pyproject.toml:

```toml
[project]
name = "blah"
version = "0.0.1"
dependencies = [
    "requests",
]
[project.optional-dependencies]
test = [
    "pytest",
]
```

If I run `pip-compile --output-file requirements-test.txt pyproject.toml --extra test`, I get 

```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --extra=test --output-file=requirements-test.txt --resolver=backtracking pyproject.toml
#
certifi==2022.12.7
    # via requests
charset-normalizer==3.1.0
    # via requests
idna==3.4
    # via requests
iniconfig==2.0.0
    # via pytest
packaging==23.1
    # via pytest
pluggy==1.0.0
    # via pytest
pytest==7.3.1
    # via blah (pyproject.toml)
requests==2.28.2
    # via blah (pyproject.toml)
urllib3==1.26.15
    # via requests
```

You can't tell any difference in source between pytest and requests. Ideally, I would like to see something like this for pytest:

```
...
pytest==7.3.1
    # via blah[test] (pyproject.toml)
...
```

or

```
...
pytest==7.3.1
    # via blah (pyproject.toml[test])
...
```

Would that be feasible?
