### ISSUE TITLE
[Bug/Question] pip-compile does not include package

### ISSUE THREAD

**Issue by paw-lu** [jazzband/pip-tools#1905]
#### Environment Versions

1. OS Type: macOS
1. Python version: 3.11.1
1. pip version: 22.3.1
1. pip-tools version: 6.14.0

#### Steps to replicate

With project format:

```txt
.
├── dev-requirements.txt
├── pyproject.toml
├── requirements.txt
└── src
    └── my_package
        ├── __init__.py
        └── foo.py
```

and a `pyproject.toml` of:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_package"
version = "0.1"
requires-python = ">=3.11"
dependencies = ["holidays"]

[tool.hatch.build.targets.wheel]
packages = ["src/my_package"]

[project.optional-dependencies]
dev = ["black", "mypy", "ruff", "ipykernel", "pyupgrade"]
```

#### Expected result

Similar to what happends if we use hatch natively.

```sh
$ hatch env create
$ hatch env run python
>>> import my_package
>>>
```

I expected my local package to be installed, ideally in editable (`-e`) mode.

#### Actual result

Running pip-compile does not seem to install the local package, `my_package`.

```sh
$ pip-compile -o requirements.txt pyproject.toml
$ pip-sync requirements.txt dev-requirement.txt
$ python
>>> import my_package
ModuleNotFoundError: No module named 'my_package'
```

---

I'm very new to pip-tools, so I honestly assume I'm missing a key step here, is there a suggested way or option to install the local package here?
