### ISSUE TITLE
Pre-commit cannot output requirements file into a directory

### ISSUE THREAD

**Issue by ylhan** [jazzband/pip-tools#1995]
`pip-compile` pre-commit hook cannot output requirements into a folder

#### Environment Versions

1. OS Type
1. Python version: `Python 3.10.13`
1. pip version: `pip 23.2.1`
2. pip-tools version: `7.3.0`

#### Steps to replicate
Directory structure
```
airflow
└── requirements
    └── requirements.dev.in
    └── requirements.in
    └── requirements.dev.txt
    └── requirements.txt
```

`.pre-commit-config.yaml`:
``` yaml
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.dev.in
        args:
          [
            -o requirements/requirements.dev.in,
            --strip-extras,
            requirements/requirements.dev.in,
          ]
        files: ^.*requirements\.dev\.(in|txt)$
```
#### Expected result
pre-commit updates `requirements/requirements.dev.in`

#### Actual result
```
pip-compile requirements.dev.in..........................................Failed
- hook id: pip-compile
- exit code: 1
Error: Could not open file ' requirements/requirements.dev.in': No such file or directory
```
