### ISSUE TITLE
`pre-commit`'s `pip-compile` differs between github action and local run

### ISSUE THREAD

**Issue by ylhan** [jazzband/pip-tools#1996]
`pre-commit`'s `pip-compile` differs between github action and local run. 
#### Environment Versions

1. OS Type
1. Python version: `Python 3.10.13`
1. pip version: `pip 23.2.1`
2. pip-tools version: `7.3.0`

#### Steps to replicate

`.pre-commit-config.yaml`:
``` yaml
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args:
          [
            --strip-extras,
            requirements/requirements.in,
          ]
        files: ^.*requirements\.dev\.(in|txt)$
```

`requirements.in`:
```
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt"

apache-airflow==2.6.3
```

I am using python 3.10.13 both locally and in GHA
#### Expected result
GHA should succeed and no diff should be detected. 

#### Actual result
There's an extra dependency `greenlet` added when run through GHA.
![image](https://github.com/jazzband/pip-tools/assets/23009089/195b4df0-80cd-4bf8-b2f8-64d600eae038)
