### ISSUE TITLE
pre-commit hook not picking all the pyproject.toml files in the repo

### ISSUE THREAD

**Issue by Opalo** [jazzband/pip-tools#2001]
I've the following repository layout:
```
- libs/
  - l1/
   - pyproject.toml
  - l2/
   - pyproject.toml

- batch/
  - b1/
   - pyproject.toml
  - b2/
   - pyproject.toml

- pipelines/
  - p1/
   - pyproject.toml
  - p2/
   - pyproject.toml

- pyproject.toml
```
and the following `pre-commit` hook defined:
```
---
files: .(yaml|yml|py|toml)$
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: Run pip-compile for 'prod' env.
        args:
          - -o
          - pyproject.lock
          - --generate-hashes
          - --strip-extras
```

But for some reason it does not pick all the `pyproject.toml` files - it only picks the one in the root folder. Why is that? I was trying to configure `files:` option for the hook to no avail. From my research I see that I'd need to create the hook conf for each file separately - is this a case?

#### Environment Versions

1. OS: `macOS Darwin opalmac.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64`
1. Python version: `Python 3.9.16`
1. pip version: `pip 23.2.1`
1. pip-tools version: `7.3.0`

#### Steps to replicate

You can play around with [this](https://github.com/Opalo/pip-tools) repository. With the current settings no `pyproject.toml` files is being "locked". If I add `files: pyproject.toml` only the root file will be processed.

#### Expected result

All the `pyproject.toml` files in the repo have locked dependencies.

#### Actual result

None of the `pyproject.toml` files in the repo have locked dependencies.
