### ISSUE TITLE
`pip-compile requirements.in` produces a different output than the pre-commit hook.

### ISSUE THREAD

**Issue by PawelPawlikMIM** [jazzband/pip-tools#2034]
In version 7.3.0 `pip-compile requirements.in` produces a different output than the pre-commit hook.
The is no issue after downgrading to 7.2.0.

#### Environment Versions

1. OS Type: Ubuntu 20.04.3 LTS 
1. Python version: Python 3.9.5
1. pip version: pip 23.3
1. pip-tools version: 7.3.0

#### Steps to replicate

1. `requirements.in` content:
```
selenium==4.14.0
```
2. `.pre-commit-config.yaml` content:
```
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        files: ^requirements\.(in|txt)$
        args: [requirements.in]
```
3. commit  `requirements.in` file
4. run `pip-compile requirements.in`

#### Expected result

`requirements.txt` should remain unchanged when running the 4th step.

#### Actual result

`requirements.txt` differs. `diff` output:
```
 urllib3[socks]==1.26.16
-    # via selenium
+    # via
+    #   selenium
+    #   urllib3
 wsproto==1.2.0
```
