### ISSUE TITLE
pip-sync should respect pip-compile's output_file configuration

### ISSUE THREAD

**Issue by aentwist** [jazzband/pip-tools#2093]
#### Expected result

```toml
[tool.pip-tools]
src_files = ["requirements.in", "dev-requirements.in"]
output_file = "requirements-lock.txt"

```

pip-sync syncs from requirements-lock.txt

#### Actual result

looks for requirements.txt

#### Steps to replicate

1. use undocumented configuration src_files, and configuration output_file
2. pip-compile
3. pip-sync

#### Proposed Solution

respect the output file

#### Alternative Considerations

add a pip-sync option

###### OS Type

WSL2 Debian 12

###### Python version: `$ python -V`

3.10.14

###### pip version: `$ pip --version`

23.0.1

###### pip-tools version: `$ pip-compile --version`

7.4.1
