### ISSUE TITLE
pip-compile should not generate a command with --output-file if the output file matches the configuration

### ISSUE THREAD

**Issue by aentwist** [jazzband/pip-tools#2094]
## Expected

*pyproject.toml*

```toml
[tool.pip-tools]
src_files = ["requirements.in", "dev-requirements.in"]
output_file = "requirements-lock.txt"

```

output command is `pip-compile`

## Actual

```txt
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --output-file=requirements-lock.txt
#
```

---

very low prio
