### ISSUE TITLE
pre-commit hook for pip-compile

### ISSUE THREAD

**Issue by anukul** [jazzband/pip-tools#974]
#### What's the problem this feature will solve?

Running `pip-compile` to ensure that `requirements.txt` is in sync with `setup.py`

#### Describe the solution you'd like

A [pre-commit](https://pre-commit.com/) hook for this purpose, so users don't have to do this manually

At this point, a CI check will fail if `pip-compile` generates a modified `requirements.txt` than what is present in the source, to indicate to the user that they should do this on their end.
This is conceptually similar to running a linter like [black](https://github.com/psf/black) etc which have pre-commit hooks for this purpose, so it makes sense that `pip-compile` could have one too.

**Comment by atugushev** [comment]
Hello @anukul,

Thanks for submitting the issue! I'm a big fan of pre-commit, but I think it would make slow your commit command since pip-compile does a lot of heavy stuff and touches the network. Commit hooks are supposed to be fast in an ideal world. 

I would suggest running pip-compile (as a CI check) on a daily cron job, rather than in a commit hook.

**Comment by cb109** [comment]
I agree this would be too slow for a `pre-commit` hook. Could make sense as a `pre-push` hook though, assuming you push just a few times a day at max.

A possible setup with your `.pre-commit-config.yaml` could look like this: 

```yml
repos:

- repo: local
  hooks:
  - id: pip-compile
    name: compile requirements.txt
    entry: pip-compile
    language: system
    always_run: false
    files: requirements.in|setup.py$
    stages: [push]
```

To make `stages: [push]` have an effect, don't forget to install the `pre-push` hook type (default is `pre-commit`): 

```bash
$ pre-commit install --install-hooks --overwrite --hook-type pre-push
```
